version: '3.8'

services:
  my-db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      TZ: Asia/Seoul
    volumes:
      # - ./mysql_data:/var/lib/mysql # load failed 가 됨!
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10
    networks:
      - test_network

  my-server:
    restart: on-failure
    # .env 파일을 로드하여 환경변수를 설정
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - my-db
#    condition: service_healthy
    networks:
      - test_network
networks:
  test_network:
    driver: bridge