server:
  port: 8080


spring:
  config:
    import: optional:file:.env[.properties] # .env 파일 로드

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update # 테이블 생성 및 업데이트 전략 (create, create-drop, update, validate, none)
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        highlight_sql: true # 하이라이트 SQL 출력
        use_sql_comments: true # 실제 JPQL SQL 주석 사용

app:
  aws:
    ec2:
        instance-front-url: ${AWS_EC2_INSTANCE_FRONT_URL}


logging:
  level:
#    org.springframework.security.web: trace
    org.hibernate.SQL: debug # Hibernate의 SQL을 출력
    org.hibernate.orm.jdbc.bind: trace # Hibernate의 SQL 바인딩을 출력
    org.springframework.transaction.interceptor: trace # Hibernate의 SQL 바인딩을 출력



