server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update # ??? ?? ? ???? ?? (create, create-drop, update, validate, none)
    properties:
      hibernate:
        format_sql: true # SQL ???
        highlight_sql: true # ????? SQL ??
        use_sql_comments: true # ?? JPQL SQL ?? ??

logging:
  level:
#    org.springframework.security.web: trace
    org.hibernate.SQL: debug # Hibernate? SQL? ??
    org.hibernate.orm.jdbc.bind: trace # Hibernate? SQL ???? ??
    org.springframework.transaction.interceptor: trace # Hibernate? SQL ???? ??



