name: Deploy To EC2 docker-compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: test241212

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/${{ env.REPOSITORY_NAME }}
            sudo git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
            
